CopyrightBranch.create(id: CopyrightBranch::LITERARY, name: 'Literaria')
CopyrightBranch.create(id: CopyrightBranch::MUSICAL_LYRICS, name: 'Musical con letra')
CopyrightBranch.create(id: CopyrightBranch::MUSICAL_NOT_LYRICS, name: 'Musical sin letra')
CopyrightBranch.create(id: CopyrightBranch::DRAMATIC, name: 'Dramática')
CopyrightBranch.create(id: CopyrightBranch::DANCE, name: 'Danza')
CopyrightBranch.create(id: CopyrightBranch::PICTORIC, name: 'Pictórica')
CopyrightBranch.create(id: CopyrightBranch::DRAWING, name: 'Dibujo')
CopyrightBranch.create(id: CopyrightBranch::SCULPTOR, name: 'Escultórica')
CopyrightBranch.create(id: CopyrightBranch::PLASTIC_CHARACTER, name: 'De carácter plástico')
CopyrightBranch.create(id: CopyrightBranch::CARTOON, name: 'Caricatura')
CopyrightBranch.create(id: CopyrightBranch::STORIETTE, name: 'Historieta')
CopyrightBranch.create(id: CopyrightBranch::ARCHITECTURAL, name: 'Arquitectónica')
CopyrightBranch.create(id: CopyrightBranch::CINEMATOGRAPHY, name: 'Cinematográfica')
CopyrightBranch.create(id: CopyrightBranch::AUDIOVISUAL, name: 'Audiovisual')
CopyrightBranch.create(id: CopyrightBranch::RADIO_SHOW, name: 'Programa de radio')
CopyrightBranch.create(id: CopyrightBranch::TV_SHOW, name: 'Programa de televisión')
CopyrightBranch.create(id: CopyrightBranch::COMPUTER_PROGRAM, name: 'Programa de cómputo')
CopyrightBranch.create(id: CopyrightBranch::PHOTO, name: 'Fotográfica')
CopyrightBranch.create(id: CopyrightBranch::APPLIED_ART, name: 'Arte aplicado')
CopyrightBranch.create(id: CopyrightBranch::DATABASE, name: 'Base de datos')