# Codificación:utf-8

Country.delete_all
countryInserts = []

countryInserts.push "(1,'AD','Andorra')"
countryInserts.push "(2,'AE','Emiratos Árabes Unidos')"
countryInserts.push "(3,'AF','Afganistán')"
countryInserts.push "(4,'AG','Antigua y Barbuda')"
countryInserts.push "(5,'AI','Anguila')"
countryInserts.push "(6,'AL','Albania')"
countryInserts.push "(7,'AM','Armenia')"
countryInserts.push "(8,'AO','Angola')"
countryInserts.push "(9,'AQ','La Antártida')"
countryInserts.push "(10,'AR','Argentina')"
countryInserts.push "(11,'AS','Samoa Americana')"
countryInserts.push "(12,'AT','Austria')"
countryInserts.push "(13,'AU','Australia')"
countryInserts.push "(14,'AW','Aruba')"
countryInserts.push "(15,'AX','Islas de Aland')"
countryInserts.push "(16,'AZ','Azerbaiyán')"
countryInserts.push "(17,'BA','Bosnia y Herzegovina')"
countryInserts.push "(18,'BB','Barbados')"
countryInserts.push "(19,'BD','Bangladesh')"
countryInserts.push "(20,'SER','Bélgica')"
countryInserts.push "(21,'BF','Burkina Faso')"
countryInserts.push "(22,'BG','Bulgaria')"
countryInserts.push "(23,'BH','Bahrein')"
countryInserts.push "(24,'BI','Burundi')"
countryInserts.push "(25,'BJ','Benin')"
countryInserts.push "(26,'BL','San Bartolomé')"
countryInserts.push "(27,'BM','Bermuda')"
countryInserts.push "(28,'BN','Brunei')"
countryInserts.push "(29,'BO','Bolivia')"
countryInserts.push "(30,'BQ','Bonaire, San Eustaquio y Saba')"
countryInserts.push "(31,'BR','Brasil')"
countryInserts.push "(32,'BS','Bahamas')"
countryInserts.push "(33,'BT','Bhutan')"
countryInserts.push "(34,'BV','Isla Bouvet')"
countryInserts.push "(35,'BW','Botswana')"
countryInserts.push "(36,'POR','Belarús')"
countryInserts.push "(37,'BZ','Belice')"
countryInserts.push "(38,'CA','Canadá')"
countryInserts.push "(39,'CC','Islas Cocos')"
countryInserts.push "(40,'CD','República Democrática del Congo')"
countryInserts.push "(41,'CF','República de África Central')"
countryInserts.push "(42,'CG','República del Congo')"
countryInserts.push "(43,'CH','Suiza')"
countryInserts.push "(44,'CI','Costa de Marfil')"
countryInserts.push "(45,'CK','Islas Cook')"
countryInserts.push "(46,'CL','Chile')"
countryInserts.push "(47,'CM','Camerún')"
countryInserts.push "(48,'CN','China')"
countryInserts.push "(49,'CO','Colombia')"
countryInserts.push "(50,'CR','Costa Rica')"
countryInserts.push "(51,'CU','Cuba')"
countryInserts.push "(52,'CV','Cabo Verde')"
countryInserts.push "(53,'CW','Curazao')"
countryInserts.push "(54,'CX','Isla de Navidad')"
countryInserts.push "(55,'CY','Chipre')"
countryInserts.push "(56,'CZ','República Checa')"
countryInserts.push "(57,'DE','Alemania')"
countryInserts.push "(58,'DJ','Djibouti')"
countryInserts.push "(59,'DK','Dinamarca')"
countryInserts.push "(60,'DM','Dominica')"
countryInserts.push "(61,'DO','República Dominicana')"
countryInserts.push "(62,'DZ','Argelia')"
countryInserts.push "(63,'CE','Ecuador')"
countryInserts.push "(64,'EE','Estonia')"
countryInserts.push "(65,'EG','Egipto')"
countryInserts.push "(66,'EH','Sáhara Occidental')"
countryInserts.push "(67,'ER','Eritrea')"
countryInserts.push "(68,'ES','España')"
countryInserts.push "(69,'ET','Etiopía')"
countryInserts.push "(70,'FI','Finlandia')"
countryInserts.push "(71,'FJ','Fiji')"
countryInserts.push "(72,'FK','Islas Malvinas')"
countryInserts.push "(73,'FM','Micronesia')"
countryInserts.push "(74,'FO','Islas Feroe')"
countryInserts.push "(75,'FR','Francia')"
countryInserts.push "(76,'GA','Gabón')"
countryInserts.push "(77,'GB','Reino Unido')"
countryInserts.push "(78,'GD','Grenada')"
countryInserts.push "(79,'GE','Georgia')"
countryInserts.push "(80,'GF','Guyana')"
countryInserts.push "(81,'GG','Guernesey')"
countryInserts.push "(82,'GH','Ghana')"
countryInserts.push "(83,'GI','Gibraltar')"
countryInserts.push "(84,'GL','Groenlandia')"
countryInserts.push "(85,'GM','Gambia')"
countryInserts.push "(86,'GN','Guinea')"
countryInserts.push "(87,'GP','Guadalupe')"
countryInserts.push "(88,'GQ','Guinea Ecuatorial')"
countryInserts.push "(89,'GR','Grecia')"
countryInserts.push "(90,'GS','Georgia del Sur y las Islas Sandwich del Sur')"
countryInserts.push "(91,'GT','Guatemala')"
countryInserts.push "(92,'GU','Guam')"
countryInserts.push "(93,'GW','Guinea-Bissau')"
countryInserts.push "(94,'GY','Guyana')"
countryInserts.push "(95,'HK','Hong Kong')"
countryInserts.push "(96,'HM','Islas Heard y McDonald')"
countryInserts.push "(97,'HN','Honduras')"
countryInserts.push "(98,'HR','Croacia')"
countryInserts.push "(99,'HT','Haití')"
countryInserts.push "(100,'HU','Hungría')"
countryInserts.push "(101,'ID','Indonesia')"
countryInserts.push "(102,'IE','Irlanda')"
countryInserts.push "(103,'IL','Israel')"
countryInserts.push "(104,'IM','Isla de Man')"
countryInserts.push "(105,'IN','La India')"
countryInserts.push "(106,'IO','Territorio Británico del Océano Índico')"
countryInserts.push "(107,'IQ','Irak')"
countryInserts.push "(108,'IR','Irán')"
countryInserts.push "(109,'ES','Islandia')"
countryInserts.push "(110,'IT','Italia')"
countryInserts.push "(111,'JE','Jersey')"
countryInserts.push "(112,'JM','Jamaica')"
countryInserts.push "(113,'JO','Jordan')"
countryInserts.push "(114,'JP','Japón')"
countryInserts.push "(115,'KE','Kenia')"
countryInserts.push "(116,'KG','Kirguistán')"
countryInserts.push "(117,'KH','Camboya')"
countryInserts.push "(118,'KI','Kiribati')"
countryInserts.push "(119,'KM','Comoras')"
countryInserts.push "(120,'KN','San Cristóbal y Nieves')"
countryInserts.push "(121,'KP','Corea del Norte')"
countryInserts.push "(122,'KR','Corea del Sur')"
countryInserts.push "(123,'XK','Kosovo')"
countryInserts.push "(124,'KW','Kuwait')"
countryInserts.push "(125,'KY','Islas Caimán')"
countryInserts.push "(126,'KZ','Kazajstán')"
countryInserts.push "(127,'LA','Laos')"
countryInserts.push "(128,'LB','Líbano')"
countryInserts.push "(129,'LC','Santa Lucía')"
countryInserts.push "(130,'LI','Liechtenstein')"
countryInserts.push "(131,'LK','Sri Lanka')"
countryInserts.push "(132,'LR','Liberia')"
countryInserts.push "(133,'LS','Lesotho')"
countryInserts.push "(134,'LT','Lituania')"
countryInserts.push "(135,'LU','Luxemburgo')"
countryInserts.push "(136,'LV','Letonia')"
countryInserts.push "(137,'LY','Libia')"
countryInserts.push "(138,'MA','Marruecos')"
countryInserts.push "(139,'MC','Mónaco')"
countryInserts.push "(140,'MD','Moldavia')"
countryInserts.push "(141,'ME','Montenegro')"
countryInserts.push "(142,'MF','San Martín')"
countryInserts.push "(143,'MG','Madagascar')"
countryInserts.push "(144,'MH','Islas Marshall')"
countryInserts.push "(145,'MK','Macedonia')"
countryInserts.push "(146,'ML','Mali')"
countryInserts.push "(147,'MM','Myanmar')"
countryInserts.push "(148,'MN','Mongolia')"
countryInserts.push "(149,'MO','Macao')"
countryInserts.push "(150,'MP','Islas Marianas del Norte')"
countryInserts.push "(151,'MQ','Martinica')"
countryInserts.push "(152,'MR','Mauritania')"
countryInserts.push "(153,'MS','Montserrat')"
countryInserts.push "(154,'MT','Malta')"
countryInserts.push "(155,'MU','Mauricio')"
countryInserts.push "(156,'MV','Maldivas')"
countryInserts.push "(157,'MW','Malawi')"
countryInserts.push "(158,'MX','México')"
countryInserts.push "(159,'MI','Malasia')"
countryInserts.push "(160,'MZ','Mozambique')"
countryInserts.push "(161,'NA','Namibia')"
countryInserts.push "(162,'NC','Nueva Caledonia')"
countryInserts.push "(163,'NE','Níger')"
countryInserts.push "(164,'NF','Isla de Norfolk')"
countryInserts.push "(165,'NG','Nigeria')"
countryInserts.push "(166,'NI','Nicaragua')"
countryInserts.push "(167,'NL','Países Bajos')"
countryInserts.push "(168,'NO','Noruega')"
countryInserts.push "(169,'NP','Nepal')"
countryInserts.push "(170,'NR','Nauru')"
countryInserts.push "(171,'NU','Niue')"
countryInserts.push "(172,'NZ','Nueva Zelanda')"
countryInserts.push "(173,'OM','Omán')"
countryInserts.push "(174,'PA','Panamá')"
countryInserts.push "(175,'PE','Perú')"
countryInserts.push "(176,'PF','Polinesia Francesa')"
countryInserts.push "(177,'PG','Papúa Nueva Guinea')"
countryInserts.push "(178,'PH','Filipinas')"
countryInserts.push "(179,'PK','Pakistán')"
countryInserts.push "(180,'PL','Polonia')"
countryInserts.push "(181,'PM','San Pedro y Miquelón')"
countryInserts.push "(182,'PN','Pitcairn')"
countryInserts.push "(183,'PR','Puerto Rico')"
countryInserts.push "(184,'PS','territorio palestino')"
countryInserts.push "(185,'PT','Portugal')"
countryInserts.push "(186,'PW','Palau')"
countryInserts.push "(187,'PY','Paraguay')"
countryInserts.push "(188,'QA','Qatar')"
countryInserts.push "(189,'RE','Reunion')"
countryInserts.push "(190,'RO','Rumania')"
countryInserts.push "(191,'RS','Serbia')"
countryInserts.push "(192,'RU','Rusia')"
countryInserts.push "(193,'RW','Rwanda')"
countryInserts.push "(194,'SA','Arabia Saudita')"
countryInserts.push "(195,'SB','Islas Salomón')"
countryInserts.push "(196,'SC','Seychelles')"
countryInserts.push "(197,'SD','Sudán')"
countryInserts.push "(198,'SE','Suecia')"
countryInserts.push "(199,'SG','Singapur')"
countryInserts.push "(200,'SH','Santa Helena')"
countryInserts.push "(201,'SI','Eslovenia')"
countryInserts.push "(202,'SJ','Svalbard y Jan Mayen')"
countryInserts.push "(203,'SK','Eslovaquia')"
countryInserts.push "(204,'SL','Sierra Leona')"
countryInserts.push "(205,'SM','San Marino')"
countryInserts.push "(206,'SN','Senegal')"
countryInserts.push "(207,'SO','Somalia')"
countryInserts.push "(208,'SR','Suriname')"
countryInserts.push "(209,'ST','Santo Tomé y Príncipe')"
countryInserts.push "(210,'SV','El Salvador')"
countryInserts.push "(211,'SX','Sint Maarten')"
countryInserts.push "(212,'SY','Siria')"
countryInserts.push "(213,'SZ','Swazilandia')"
countryInserts.push "(214,'TC','Islas Turcas y Caicos')"
countryInserts.push "(215,'TD','Chad')"
countryInserts.push "(216,'TF','Territorios Australes Franceses')"
countryInserts.push "(217,'TG','Togo')"
countryInserts.push "(218,'TH','Tailandia')"
countryInserts.push "(219,'TJ','Tayikistán')"
countryInserts.push "(220,'TK','Tokelau')"
countryInserts.push "(221,'TL','Timor Oriental')"
countryInserts.push "(222,'TM','Turkmenistán')"
countryInserts.push "(223,'TN','Túnez')"
countryInserts.push "(224,'A','Tonga')"
countryInserts.push "(225,'TR','Turquía')"
countryInserts.push "(226,'TT','Trinidad y Tobago')"
countryInserts.push "(227,'TV','Tuvalu')"
countryInserts.push "(228,'TW','Taiwan')"
countryInserts.push "(229,'TZ','Tanzania')"
countryInserts.push "(230,'UA','Ucrania')"
countryInserts.push "(231,'UG','Uganda')"
countryInserts.push "(232,'UM','Estados Unidos Islas menores alejadas')"
countryInserts.push "(233,'US','Estados Unidos')"
countryInserts.push "(234,'UY','Uruguay')"
countryInserts.push "(235,'UZ','Uzbekistán')"
countryInserts.push "(236,'VA','Vaticano')"
countryInserts.push "(237,'VC','San Vicente y las Granadinas')"
countryInserts.push "(238,'VE','Venezuela')"
countryInserts.push "(239,'VG','Islas Vírgenes Británicas')"
countryInserts.push "(240,'VI','Islas Vírgenes de Estados Unidos')"
countryInserts.push "(241,'VN','Vietnam')"
countryInserts.push "(242,'VU','Vanuatu')"
countryInserts.push "(243,'WF','Wallis y Futuna')"
countryInserts.push "(244,'WS','Samoa')"
countryInserts.push "(245,'YE','Yemen')"
countryInserts.push "(246,'YT','Mayotte')"
countryInserts.push "(247,'ZA','Sudáfrica')"
countryInserts.push "(248,'ZM','Zambia')"
countryInserts.push "(249,'ZW','Zimbabwe')"
countryInserts.push "(250,'CS','Serbia y Montenegro')"
countryInserts.push "(251,'UN','Antillas Holandesas')"

sqlCountry = "INSERT INTO countries (id, iso, name) VALUES #{countryInserts.join(", ")}"
Country.connection.execute(sqlCountry)