class CopyrightBranch < ActiveRecord::Base
  has_many :copyright, dependent: :destroy

  # Ramas

  LITERARY = 1
  MUSICAL_LYRICS = 2
  MUSICAL_NOT_LYRICS = 3
  DRAMATIC = 4
  DANCE = 5
  PICTORIC = 6
  DRAWING = 7
  SCULPTOR = 8
  PLASTIC_CHARACTER = 9
  CARTOON = 10
  STORIETTE = 11
  ARCHITECTURAL = 12
  CINEMATOGRAPHY = 13
  AUDIOVISUAL = 14
  RADIO_SHOW = 15
  TV_SHOW = 16
  COMPUTER_PROGRAM = 17
  PHOTO = 18
  APPLIED_ART = 19
  DATABASE = 20

end
